FROM nginx:latest

## Timezon
ENV TZ Asia/Tokyo
RUN echo "${TZ}" > /etc/timezone \
   && dpkg-reconfigure -f noninteractive tzdata


## Nginx Setting
ADD ./docker/nginx/site.conf /etc/nginx/conf.d/default.conf
ADD ./docker/nginx/nginx.conf /etc/nginx/nginx.conf

RUN usermod -u 1000 www-data
RUN groupmod -g 1000 www-data

RUN mkdir -p /var/www/html/src/public
ADD ./public/ /var/www/html/src/public/
