@if($content['c_flag'] == 'seeker')
<p>求職者からのお問い合わせ</p>
<p>
……………………………………………………………………………<br>
　以下の内容でお問い合わせを受けました。<br>
　ご返答は3営業日以内にお願いいたします。<br>
……………………………………………………………………………<br>
</p>
<p>
【お問い合わせカテゴリ】<br>
 {{$content['category']}}
</p>
<p>
【氏名】<br>
 {{$content['name']}}
</p>
<p>
【氏名(フリガナ)】<br>
 {{$content['name_ruby']}}
</p>
<p>
【返信先メールアドレス】<br>
 {{$content['email']}}
</p>
<p>
【連絡先電話番号】<br>
 {{$content['phone']}}
</p>
<p>
【お問い合わせ内容】<br>
 {{$content['content']}}
</p>

@elseif($content['c_flag'] == 'employer')
<p>企業担当者からのお問い合わせ</p>
<p>
……………………………………………………………………………<br>
　以下の内容でお問い合わせを受けました。<br>
　ご返答は3営業日以内にお願いいたします。<br>
……………………………………………………………………………<br>
<p>
【お問い合わせカテゴリ】<br>
 {{$content['category']}}
</p>
<p>
【企業名】<br>
 {{$content['cname']}}
</p>
<p>
【企業名(フリガナ)】<br>
 {{$content['cname_katakana']}}
</p>
<p>
【担当者名】<br>
 {{$content['name']}}
</p>
<p>
【担当者名(フリガナ)】<br>
 {{$content['name_ruby']}}
</p>
<p>
【返信先メールアドレス】<br>
 {{$content['email']}}
</p>
<p>
【連絡先電話番号】<br>
 {{$content['phone']}}
</p>
<p>
【お問い合わせ内容】<br>
 {{$content['content']}}
</p>
@endif

<p>─────────────────────────────────</p>
<p>JOB CiNEMAからのお問い合わせです</p>
